image: docker:dind

services:
  - name: docker:dind

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t my-image .

test:
  stage: test
  script:
    - docker-compose up -d
    - sleep 10 # Attendre 10 secondes pour que le service soit opérationnel
    - docker-compose -f docker-compose.yml exec nest-test npm run test:e2e
