image: docker:dind

services:
  - name: docker:dind

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t my-image .

test:
  stage: test
  script:
    - docker build -t my-image .
    - docker-compose up -d
    - docker-compose -f docker-compose.yml exec nest-test npm run test:e2e
