image: docker:dind

services:
  - name: docker:dind

stages:
  - build

build:
  stage: build
  script:
    - docker build -t skurt .
    - docker compose up -d
    - docker-compose exec nestjs-api npm run test:docker:e2e