version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_db: nest
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_db: nest
    networks:
      - freecodecamp
  my-image:
    image: my-image # Utilisez le nom de votre image construite
    container_name: nest-test
    restart: no
    ports:
      - "3001:3001"
    depends_on:
      - test-db # Dépendance sur le service test-db
    command: npm run test:e2e # Commande pour exécuter les tests E2E
    networks:
      - freecodecamp
networks:
  freecodecamp:
