version: '3.8'

services:

  postgres:
    image: postgres:13
    ports: 
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_db: nest
    networks:
      - postgres

  nestjs-api:
    image: skurt
    env_file:
      - .env
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
